### PR TITLE
Display actual classNN for current control

### PR DESCRIPTION
**Pull request by livtanong**
Currently it just shows what appears to be the ID of that instance of control

### CODE REVIEW

**Comment by steelywing** [comment]
Merged

**Comment by livtanong** [comment]
@steelywing According to github, you closed this PR without merging. I'm not complaining, just want to clarify because you said "Merged", so I'm a bit confused.

**Comment by steelywing** [comment]
Sorry, because I rewrite a lot after that and don't know how to fix the conflict, so I just add `ControlGetClassNN` to it to "Merged" it.

**Comment by livtanong** [comment]
Ahh, okay that makes sense! :D

**Pull request closed without merging**
